#!/usr/bin/env node
// One-off helper for Slice 6 RO translation pass. Merges new
// `pages`, `appFeatures`, and `dashboard` namespaces into the existing
// en.json + ro.json without touching other namespaces.
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const here = path.dirname(url.fileURLToPath(import.meta.url));
const enPath = path.resolve(here, '..', 'messages', 'en.json');
const roPath = path.resolve(here, '..', 'messages', 'ro.json');

const en = {
  pages: {
    ask: {
      title: 'Ask Notai',
      subtitle: '· search and reason across all your notes',
    },
    calendar: {
      title: 'Calendar',
      subtitle: 'See when you wrote what. Click a day to jump back.',
    },
    calendars: {
      metaTitle: 'Calendars',
      back: 'Back',
      title: 'Calendars',
      description:
        'Subscribe to a calendar via its public iCal/webcal URL. Events from the next 7 days will show on your dashboard. Read-only — Notai never writes back to the calendar source.',
      helpSummary: 'Where do I find the iCal URL?',
      helpGoogleLabel: 'Google Calendar',
      helpGoogleBody:
        ': Settings → your calendar → "Secret address in iCal format". Treat the URL as a password.',
      helpOutlookLabel: 'Outlook',
      helpOutlookBody:
        ': Settings → Calendar → Shared calendars → Publish a calendar → ICS link.',
      helpAppleLabel: 'Apple iCloud',
      helpAppleBody:
        ': Right-click a calendar → Share → Public Calendar → copy URL (replace {webcal} with {https}).',
    },
    db: {
      metaTitleIndex: 'Databases',
      metaTitleDetail: 'Database',
      back: 'Back',
      title: 'Databases',
      description:
        'Every property key you use becomes a tiny database. Open one to see all notes that share that property in a sortable table.',
      empty:
        'No properties yet. Open any note and add one from the Properties panel below the editor.',
      noteCountOne: '{count} note',
      noteCountOther: '{count} notes',
      rowCountOne: '{count} note with this property.',
      rowCountOther: '{count} notes with this property.',
      allDatabases: 'All databases',
      otherDatabases: 'Other databases',
    },
    emailIn: {
      metaTitle: 'Email-to-note',
      back: 'Back',
      title: 'Email-to-note',
      description:
        'Forward or compose an email to your secret address; the subject becomes the note title and the body becomes the note. Only mail from your account email address is accepted.',
      notConfigured:
        "Inbound email isn't configured on this deployment yet ({var} not set). Your address is shown for preview but mail to it won't arrive.",
      helpSummary: 'How does this work?',
      helpBullet1:
        'The {token} in your address routes mail to your account. Treat it like a password — anyone who knows it can create notes in your account.',
      helpBullet2: 'Mail must come from your account email; spoofed senders are rejected.',
      helpBullet3: 'HTML emails are converted to plain text. Attachments are not yet stored.',
    },
    folder: {
      metaTitle: 'Folder',
      noteCountOne: '{count} note',
      noteCountOther: '{count} notes',
      subfolderCountOne: '{count} subfolder',
      subfolderCountOther: '{count} subfolders',
      newSticky: 'New sticky',
      newNote: 'New note',
      pinned: 'Pinned',
      allNotes: 'All notes',
      emptyTitle: 'This folder is empty',
      emptyBody: 'Create a note inside this folder to get started.',
    },
    graph: {
      title: 'Graph',
      noteCountOne: '{count} note',
      noteCountOther: '{count} notes',
      linkCountOne: '{count} link',
      linkCountOther: '{count} links',
      subtitle: '· {notes}, {links}',
    },
    inboxZero: {
      metaTitle: 'Inbox Zero — Notai',
      title: 'Inbox Zero',
      description:
        "Notes you haven't filed yet. Notai suggests the closest folder by comparing each note to the average of every folder's contents. Accept the suggestion in one click — or pick your own.",
    },
    review: {
      metaTitle: 'Review · notai',
      title: 'Spaced repetition',
      summary: '{due} due · {total} total · {reviewed} reviewed in last 24h',
    },
    stats: {
      back: 'Back',
      title: 'Your stats',
      totalNotes: 'Total notes',
      last7Days: 'Last 7 days',
      favorites: 'Favorites',
      archived: 'Archived',
      sectionTitle30d: 'Notes created — last 30 days',
      sectionSummary30d: '{count} new notes in the last 30 days.',
      noActivity: 'No activity yet.',
      topTags: 'Top tags',
      noTags: 'No tags yet. Add #tags to notes to see them here.',
    },
    tags: {
      breadcrumbsAria: 'Tag breadcrumbs',
      all: 'All',
      noteCountOne: '{count} note',
      noteCountOther: '{count} notes',
      includesSubTags: ' (incl. sub-tags)',
      empty: 'No notes carry this tag yet.',
      untitled: 'Untitled',
    },
    templates: {
      metaTitle: 'Templates — Notai',
      title: 'Templates',
      description:
        'Start a note from a template. Designed for ADHD brains: tiny, forgiving structure that you can rewrite freely. Open any note and use the "Save as template" menu to add one of your own.',
      backToNotes: 'Back to your notes',
      searchPlaceholder: 'Search templates…',
      noMatch: 'No templates match "{query}".',
      noTemplates: 'No templates yet.',
      personalBadge: 'Personal',
      deletePersonalLabel: 'Delete personal template',
      deleteConfirm: 'Delete personal template "{title}"?',
      deleted: 'Template deleted',
      deleteFailed: 'Failed to delete',
    },
    trash: {
      back: 'Back',
      title: 'Trash',
      description: 'Notes here are permanently deleted after 30 days.',
      emptyTitle: 'Trash is empty',
      emptyBody: 'Deleted notes appear here for 30 days before being purged.',
      emptyTrashConfirm:
        'Permanently delete every note in Trash? This cannot be undone.',
      emptyTrashButton: 'Empty trash',
      deletedToday: 'today',
      deletedDaysAgoOne: '{count} day ago',
      deletedDaysAgoOther: '{count} days ago',
      purgesInOne: 'purges in {count} day',
      purgesInOther: 'purges in {count} days',
      deletedLine: 'Deleted {when} · {purge}',
      restore: 'Restore',
      restored: 'Restored',
      deleteForeverLabel: 'Delete forever',
      deleteConfirm: 'Permanently delete this note?',
      untitled: 'Untitled',
    },
    workspaces: {
      title: 'Workspaces',
      description: 'Create a team space, invite collaborators, and share folders.',
      billingMetaTitle: 'Workspace billing · notai',
      billingTitle: 'Workspace billing',
      billingDescription:
        'Per-seat subscription for this workspace. Charged per active member.',
    },
  },
  appFeatures: {
    ask: {
      stop: 'Stop',
      ask: 'Ask',
      placeholder: 'Ask anything about your notes…',
      footnote: 'Notai cites your notes by number. Click any citation to open the source.',
      emptyTitle: 'Ask your second brain',
      emptyBody:
        'Notai searches your notes with semantic similarity, then writes a grounded answer with citations to the source notes.',
      suggestion1: 'What did I learn this week?',
      suggestion2: 'Summarise my recent meeting notes',
      suggestion3: 'List every TODO scattered across my notes',
      suggestion4: 'What are my open questions about the project?',
      recentQuestions: 'Recent questions',
      searching: 'Searching your notes…',
      errorPrefix: 'Something went wrong: {error}.',
      unknownError: 'unknown error',
      stopped: 'Stopped.',
      savingAnswer: 'Saving answer…',
      answerSaved: 'Answer saved',
      saveAnswerTitle: 'Saved answer',
      saveSourcesHeader: 'Sources',
      failedCreateNote: 'Failed to create note',
      copy: 'Copy answer',
      copied: 'Copied',
      copyFailed: "Couldn't copy to clipboard",
      saveToNote: 'Save to a new note',
      sources: 'Sources:',
      untitled: 'Untitled',
    },
    graph: {
      hideEncrypted: 'Hide encrypted',
      encryptedOnly: 'Encrypted only',
      graphAria: 'Note graph',
      empty: 'No notes yet — start writing and your graph will grow.',
      noEdgesBefore: "Your notes don't reference each other yet. Type ",
      noEdgesAfter:
        ' in any note to start linking — the graph will fill in as you go.',
      someoneHere: '{name} is here',
      someone: 'Someone',
      viewerCountOther: '{count} people viewing',
      outgoingIncoming: '{out} outgoing · {in} incoming',
      moreOther: '+{count} more',
    },
    inboxZero: {
      selectedCount: '{count} selected',
      selectAll: 'Select all',
      clear: 'Clear',
      archive: 'Archive',
      moveToTrash: 'Move to Trash',
      bulkDeleteConfirmOne: 'Move {count} note to Trash?',
      bulkDeleteConfirmOther: 'Move {count} notes to Trash?',
      movedToTrash: 'Moved {count} to Trash.',
      archivedToastOne: 'Archived {count} note.',
      archivedToastOther: 'Archived {count} notes.',
      filed: 'Filed.',
      undo: 'Undo',
      undoToast: 'Move undone.',
      undoAll: 'Undo all',
      undoAllToast: 'All moves undone.',
      filedManyOne: 'Filed {count} note.',
      filedManyOther: 'Filed {count} notes.',
      readyAutoFileOne: '{count} note ready to auto-file (≥65% match).',
      readyAutoFileOther: '{count} notes ready to auto-file (≥65% match).',
      aiGistEach: 'AI gist for each',
      gistFailed: 'Could not summarise',
      fileAll: 'File all',
      fileHere: 'File here',
      suggested: 'Suggested:',
      matchPercent: '({percent}% match)',
      noClearMatch: 'No clear match — pick a folder:',
      selectAria: 'Select {title}',
      untitled: 'Untitled',
      emptyHeading: 'Inbox zero.',
      emptyBody: 'Every note is filed. Nice work.',
    },
    calendar: {
      previousMonth: 'Previous month',
      nextMonth: 'Next month',
      today: 'Today',
      weekdayMon: 'Mon',
      weekdayTue: 'Tue',
      weekdayWed: 'Wed',
      weekdayThu: 'Thu',
      weekdayFri: 'Fri',
      weekdaySat: 'Sat',
      weekdaySun: 'Sun',
      countTitleOne: '{count} note updated',
      countTitleOther: '{count} notes updated',
      loading: 'Loading…',
      noNotes: 'No notes updated this day.',
      untitled: 'Untitled',
    },
    voice: {
      title: 'Voice capture',
      stopLabel: 'Stop recording',
      recording: 'Recording — click to stop',
      transcribing: 'Transcribing…',
      requesting: 'Requesting microphone…',
      escHint: 'Press {key} to cancel',
      tooShort: 'Recording was too short.',
      saved: 'Voice note saved',
      micError: "Couldn't access your microphone",
    },
    workspace: {
      newPlaceholder: 'New workspace name…',
      create: 'Create',
      created: 'Workspace created',
      createFailed: 'Could not create',
      none: 'No workspaces yet.',
      roleOwner: 'owner',
      roleAdmin: 'admin',
      roleEditor: 'editor',
      roleViewer: 'viewer',
      memberCountOne: '{count} member',
      memberCountOther: '{count} members',
      summary: '{role} · {members}',
      manage: 'Manage',
      hide: 'Hide',
      billingTitle: 'Billing',
      deleteConfirm: 'Delete "{name}"? Members lose access immediately.',
      deleted: 'Deleted',
      failed: 'Failed',
      loading: 'Loading…',
      inviteEmailPlaceholder: 'invitee@example.com',
      roleAdminOption: 'Admin',
      roleEditorOption: 'Editor',
      roleViewerOption: 'Viewer',
      invite: 'Invite',
      inviteCopied: 'Invite link copied for {email}',
      inviteCreated: 'Invite created: {url}',
      inviteFailed: 'Could not invite',
      removeConfirm: 'Remove {who}?',
      acceptInvite: 'Accept invite',
      joined: 'Joined workspace',
      acceptFailed: 'Could not accept',
      billing: {
        current: 'Current',
        plan: 'Plan:',
        status: 'Status:',
        seats: 'Seats:',
        members: 'Members:',
        cancels: 'Cancels',
        renews: 'Renews',
        renewLine: '{verb} on {date}',
        manageTitle: 'Manage subscription',
        manageBody:
          'Change seats, switch billing cycle, or cancel from the Stripe portal.',
        openPortal: 'Open billing portal',
        upgradeTitle: 'Upgrade to Teams',
        seatsLabel: 'Seats',
        cycleLabel: 'Cycle',
        currencyLabel: 'Currency',
        monthly: 'Monthly',
        yearly: 'Yearly',
        memberCountOne: 'You have {count} member. Buy at least that many seats.',
        memberCountOther: 'You have {count} members. Buy at least that many seats.',
        checkout: 'Continue to checkout',
      },
    },
    database: {
      title: 'Title',
      empty: 'No notes carry this property yet.',
      untitled: 'Untitled',
    },
    review: {
      gradeAgainLabel: 'Again',
      gradeAgainHint: 'Forgot — show soon',
      gradeHardLabel: 'Hard',
      gradeHardHint: 'Recalled with effort',
      gradeGoodLabel: 'Good',
      gradeGoodHint: 'Recalled',
      gradeEasyLabel: 'Easy',
      gradeEasyHint: 'Trivial',
      cardAdded: 'Card added',
      deleted: 'Deleted',
      deleteConfirm: 'Delete this card?',
      tabReview: 'Review ({count})',
      tabAll: 'All cards',
      tabNew: 'New card',
      showAnswer: 'Show answer',
      noneDue: 'No cards due right now. Add some, or come back later.',
      noCards: 'No cards yet.',
      intervalDueLine: 'Interval: {days}d · Due {date}',
      delete: 'Delete',
      frontLabel: 'Front',
      backLabel: 'Back',
      frontPlaceholder: 'Question or prompt',
      backPlaceholder: 'Answer',
      addCard: 'Add card',
    },
  },
  dashboard: {
    morningBrief: {
      title: 'Morning brief',
      updatedAt: 'Updated {time}',
      privateLabel: 'Personal & private',
      saveToToday: 'Save to today',
      saveToTodayTitle: "Save into today's daily note",
      refresh: 'Refresh',
      refreshTitle: 'Regenerate',
      expand: 'Expand',
      collapse: 'Collapse',
      reading: 'Reading your recent notes…',
      drawnFrom: 'Drawn from',
      askAbout: 'Ask about this',
      askPlaceholder: "What's most urgent today?",
      ask: 'Ask',
      sectionHeading: 'Morning brief — {date}',
      ariaLabel: 'Morning brief',
    },
    throwback: {
      label: 'Throwback',
      refreshLabel: 'Show a different throwback',
      refreshTitle: 'Show a different one',
      daysAgoOne: '{count} day ago',
      daysAgoOther: '{count} days ago',
      monthsAgoOne: 'a month ago',
      monthsAgoOther: '{count} months ago',
      yearOne: 'a year ago',
      yearOther: '{count} years ago',
      yearsMonths: '{years}y {months}mo ago',
    },
    staleTodos: {
      label: 'Stale TODOs · not touched in 14+ days',
      untitled: 'Untitled',
    },
    streak: {
      titleActive: 'Day {current} of your current streak. Best ever: {best}.',
      titleInactive:
        'Your streak is at {current}. Write today to keep it alive — best ever: {best}.',
      streakLabel: '{days}-day streak',
      bestLabel: '· best {count}',
    },
    timeOfDay: {
      segmentEarlyMorning: 'Early morning',
      segmentMorning: 'Morning',
      segmentAfternoon: 'Afternoon',
      segmentEvening: 'Evening',
      segmentNight: 'Night',
      labelHours: '{hours}h {mins}m to {next}',
      labelMins: '{mins}m to {next}',
    },
    weeklyReview: {
      title: 'Weekly review',
      summary: '{touched} touched · {created} new',
      relativeToday: 'today',
      relativeYesterday: 'yesterday',
      relativeDaysAgo: '{count}d ago',
      untitled: 'Untitled',
    },
    inboxZeroNudge: {
      titleOne: '{count} unfiled note waiting',
      titleOther: '{count} unfiled notes waiting',
      body: 'File them in one pass — Notai suggests a folder for each.',
      cta: 'Inbox Zero',
    },
    continue: {
      title: 'Continue where you left off',
      untitled: 'Untitled',
      justNow: 'just now',
      minsAgo: '{count}m ago',
      hoursAgo: '{count}h ago',
      daysAgo: '{count}d ago',
    },
    dailyPrompt: {
      label: "Today's prompt",
      refreshLabel: 'Refresh prompt',
      refreshTitle: 'Generate a different prompt',
      writeAbout: 'Write about this',
      creating: 'Creating…',
      historyAria: 'Recent journal prompts',
      historyLabel: 'History',
      historyEmpty: "No past prompts yet — they'll appear here as you keep showing up.",
    },
    dailyRecap: {
      label: "Today's recap",
      summary: '{notes} · {words} words',
      noteCountOne: '{count} note',
      noteCountOther: '{count} notes',
      refreshLabel: 'Refresh recap',
      refreshTitle: 'Regenerate recap',
      saveAsNote: 'Save as note',
      noProvider: 'Connect an AI provider in Settings to get an end-of-day summary.',
    },
    sentimentHeatmap: {
      label: 'Mood, last 30 days',
      wroteOn: 'wrote on {count} of 30 days',
      tooltipPositive: '{date}: positive ({count} {noteWord})',
      tooltipTense: '{date}: tense ({count} {noteWord})',
      tooltipNeutral: '{date}: neutral ({count} {noteWord})',
      tooltipNothing: '{date}: nothing written',
      noteWordOne: 'note',
      noteWordOther: 'notes',
      footer: 'Tinted by keyword sentiment of what you wrote. Stays on your server, no external AI calls.',
    },
    openLoops: {
      label: 'Open loops',
      untitled: 'Untitled',
    },
    autoArchive: {
      bodyOne: 'note untouched for 90+ days.',
      bodyOther: 'notes untouched for 90+ days.',
      archiving: 'Archiving…',
      archiveAll: 'Archive all',
      archivedToastOne: 'Archived {count} stale note.',
      archivedToastOther: 'Archived {count} stale notes.',
      undo: 'Undo',
      undoToast: 'Archive undone.',
    },
    trashPurge: {
      bodyOne: 'note',
      bodyOther: 'notes',
      countLine: '{count} {word} in trash older than 30 days.',
      tail: 'Permanently delete to free up space?',
      working: 'Working…',
      emptyOld: 'Empty old trash',
      notNow: 'Not now',
      purgedOne: 'Permanently deleted {count} note.',
      purgedOther: 'Permanently deleted {count} notes.',
      failed: 'Could not empty trash.',
      dismiss: 'Dismiss',
    },
    todayTasks: {
      header: 'Today · {count} due',
      priorityHigh: 'high',
      priorityMed: 'med',
      priorityLow: 'low',
      estimateTitleOne: 'Estimated {count} minute',
      estimateTitleOther: 'Estimated {count} minutes',
      yesterday: 'yesterday',
      daysAgo: '{count}d ago',
      todayLabel: 'today',
      untitled: 'Untitled',
    },
    calendarToday: {
      title: 'On your calendar',
      manage: 'Manage',
      today: 'Today',
      tomorrow: 'Tomorrow',
      next7Days: 'Next 7 days',
      allDay: 'all day',
    },
    view: {
      sortUpdated: 'Recently updated',
      sortCreated: 'Recently created',
      sortOpened: 'Recently opened',
      sortAlphabetical: 'Alphabetical (A→Z)',
      sortCustom: 'Custom (drag to reorder)',
      updatedAny: 'Any time',
      updatedToday: 'Today',
      updated7d: 'Last 7 days',
      updated30d: 'Last 30 days',
      colorDefault: 'Default',
      colorYellow: 'Yellow',
      colorPink: 'Pink',
      colorBlue: 'Blue',
      colorGreen: 'Green',
      colorPurple: 'Purple',
      colorOrange: 'Orange',
      defaultName: 'Default',
      viewsLabel: 'Views',
      renameCurrent: 'Rename current',
      makeDefault: 'Make default',
      deleteCurrent: 'Delete current',
      saveAsNew: 'Save as new view…',
      saveAsNewShort: 'Save as new',
      saveView: 'Save view',
      updateView: 'Update view',
      sortLabel: 'Sort',
      sortBy: 'Sort by',
      pinnedFirst: 'Pinned first',
      filters: 'Filters',
      filterSearch: 'Search',
      filterStatus: 'Status',
      filterKind: 'Kind',
      filterUpdated: 'Updated',
      filterFolders: 'Folders',
      filterTags: 'Tags',
      filterColor: 'Color',
      filterOther: 'Other',
      searchPlaceholder: 'Title or content…',
      statusPinned: 'Pinned',
      statusPinnedOnToday: 'On Today',
      statusFavorite: 'Favorite',
      statusArchived: 'Archived',
      kindNotes: 'Notes',
      kindStickies: 'Stickies',
      noFolder: 'No folder',
      hasCollaborators: 'Has collaborators',
      reset: 'Reset',
      saveDialogTitle: 'Save view',
      saveDialogLabel: 'Name',
      saveDialogPlaceholder: 'My favorites',
      saveToast: 'View "{name}" saved',
      updateToast: 'View "{name}" updated',
      renameDialogTitle: 'Rename view',
      renameDialogLabel: 'Name',
      deleteDialogTitle: 'Delete view "{name}"?',
      deleteDialogBody: 'This cannot be undone.',
      deleteConfirm: 'Delete',
      deleteToast: 'View deleted',
      defaultToast: '"{name}" is now your default view',
      pinnedOnToday: 'Pinned on Today',
      notesHeading: 'Notes',
      noMatchTitle: 'No notes match your filters',
      noMatchBody: 'Try adjusting the filters or resetting them.',
      resetFilters: 'Reset filters',
      dragLabel: 'Drag to reorder',
      pinnedOnTodayTitle: 'Pinned on Today',
      switchedToCustom: 'Switched to custom order',
      reorderFailed: 'Reorder failed: {error}',
    },
  },
};

const ro = {
  pages: {
    ask: {
      title: 'Întreabă Notai',
      subtitle: '· caută și raționează în toate notele tale',
    },
    calendar: {
      title: 'Calendar',
      subtitle: 'Vezi când ai scris ce. Apasă o zi ca să te întorci acolo.',
    },
    calendars: {
      metaTitle: 'Calendare',
      back: 'Înapoi',
      title: 'Calendare',
      description:
        'Abonează-te la un calendar prin URL-ul public iCal/webcal. Evenimentele din următoarele 7 zile apar pe panou. Doar citire — Notai nu scrie niciodată înapoi la sursă.',
      helpSummary: 'De unde iau URL-ul iCal?',
      helpGoogleLabel: 'Google Calendar',
      helpGoogleBody:
        ': Setări → calendarul tău → „Adresă secretă în format iCal”. Tratează URL-ul ca pe o parolă.',
      helpOutlookLabel: 'Outlook',
      helpOutlookBody:
        ': Setări → Calendar → Calendare partajate → Publică un calendar → link ICS.',
      helpAppleLabel: 'Apple iCloud',
      helpAppleBody:
        ': Click dreapta pe un calendar → Partajează → Calendar public → copiază URL (înlocuiește {webcal} cu {https}).',
    },
    db: {
      metaTitleIndex: 'Baze de date',
      metaTitleDetail: 'Bază de date',
      back: 'Înapoi',
      title: 'Baze de date',
      description:
        'Fiecare cheie de proprietate pe care o folosești devine o mică bază de date. Deschide una ca să vezi toate notele care împart acea proprietate, într-un tabel sortabil.',
      empty:
        'Încă nu ai proprietăți. Deschide orice notă și adaugă una din panoul Proprietăți de sub editor.',
      noteCountOne: '{count} notă',
      noteCountOther: '{count} note',
      rowCountOne: '{count} notă cu această proprietate.',
      rowCountOther: '{count} note cu această proprietate.',
      allDatabases: 'Toate bazele de date',
      otherDatabases: 'Alte baze de date',
    },
    emailIn: {
      metaTitle: 'Email-către-notă',
      back: 'Înapoi',
      title: 'Email-către-notă',
      description:
        'Redirecționează sau scrie un email către adresa ta secretă; subiectul devine titlul notei, iar corpul devine conținutul ei. Acceptăm doar mesaje de la adresa contului tău.',
      notConfigured:
        'Emailul de intrare nu e configurat pe acest deployment ({var} nu e setat). Adresa e afișată ca previzualizare, dar mailul către ea nu va ajunge.',
      helpSummary: 'Cum funcționează?',
      helpBullet1:
        '{token} din adresă rutează mailul spre contul tău. Tratează-l ca pe o parolă — cine îl știe poate crea note în contul tău.',
      helpBullet2:
        'Mailul trebuie să vină de pe adresa contului tău; expeditorii falsificați sunt respinși.',
      helpBullet3:
        'Mailurile HTML sunt convertite în text simplu. Atașamentele nu se stochează încă.',
    },
    folder: {
      metaTitle: 'Folder',
      noteCountOne: '{count} notă',
      noteCountOther: '{count} note',
      subfolderCountOne: '{count} subfolder',
      subfolderCountOther: '{count} subfoldere',
      newSticky: 'Sticky nou',
      newNote: 'Notă nouă',
      pinned: 'Fixate',
      allNotes: 'Toate notele',
      emptyTitle: 'Folderul ăsta e gol',
      emptyBody: 'Creează o notă în el ca să începi.',
    },
    graph: {
      title: 'Graf',
      noteCountOne: '{count} notă',
      noteCountOther: '{count} note',
      linkCountOne: '{count} legătură',
      linkCountOther: '{count} legături',
      subtitle: '· {notes}, {links}',
    },
    inboxZero: {
      metaTitle: 'Inbox Zero — Notai',
      title: 'Inbox Zero',
      description:
        'Note pe care încă nu le-ai pus în foldere. Notai sugerează folderul cel mai apropiat comparând fiecare notă cu media conținutului fiecărui folder. Acceptă sugestia dintr-un click — sau alege singur.',
    },
    review: {
      metaTitle: 'Recapitulare · notai',
      title: 'Repetiție spațiată',
      summary: '{due} scadente · {total} total · {reviewed} revizuite în ultimele 24h',
    },
    stats: {
      back: 'Înapoi',
      title: 'Statisticile tale',
      totalNotes: 'Total note',
      last7Days: 'Ultimele 7 zile',
      favorites: 'Favorite',
      archived: 'Arhivate',
      sectionTitle30d: 'Note create — ultimele 30 de zile',
      sectionSummary30d: '{count} note noi în ultimele 30 de zile.',
      noActivity: 'Încă nicio activitate.',
      topTags: 'Cele mai folosite etichete',
      noTags: 'Încă nu ai etichete. Adaugă #etichete în note ca să apară aici.',
    },
    tags: {
      breadcrumbsAria: 'Pesmeți etichete',
      all: 'Toate',
      noteCountOne: '{count} notă',
      noteCountOther: '{count} note',
      includesSubTags: ' (incl. sub-etichete)',
      empty: 'Nicio notă nu poartă încă această etichetă.',
      untitled: 'Fără titlu',
    },
    templates: {
      metaTitle: 'Șabloane — Notai',
      title: 'Șabloane',
      description:
        'Pornește o notă dintr-un șablon. Gândite pentru creiere ADHD: structură mică și iertătoare pe care o poți rescrie liber. Deschide orice notă și folosește meniul „Salvează ca șablon” ca să adaugi unul de-al tău.',
      backToNotes: 'Înapoi la note',
      searchPlaceholder: 'Caută șabloane…',
      noMatch: 'Niciun șablon nu se potrivește cu „{query}”.',
      noTemplates: 'Încă niciun șablon.',
      personalBadge: 'Personal',
      deletePersonalLabel: 'Șterge șablon personal',
      deleteConfirm: 'Ștergi șablonul personal „{title}”?',
      deleted: 'Șablon șters',
      deleteFailed: 'Nu s-a putut șterge',
    },
    trash: {
      back: 'Înapoi',
      title: 'Coș de gunoi',
      description: 'Notele de aici se șterg definitiv după 30 de zile.',
      emptyTitle: 'Coșul e gol',
      emptyBody: 'Notele șterse apar aici timp de 30 de zile, apoi sunt golite.',
      emptyTrashConfirm:
        'Ștergi definitiv fiecare notă din Coș? Acțiunea nu poate fi anulată.',
      emptyTrashButton: 'Golește coșul',
      deletedToday: 'azi',
      deletedDaysAgoOne: 'acum {count} zi',
      deletedDaysAgoOther: 'acum {count} zile',
      purgesInOne: 'se golește în {count} zi',
      purgesInOther: 'se golește în {count} zile',
      deletedLine: 'Ștearsă {when} · {purge}',
      restore: 'Restaurează',
      restored: 'Restaurată',
      deleteForeverLabel: 'Șterge definitiv',
      deleteConfirm: 'Ștergi definitiv această notă?',
      untitled: 'Fără titlu',
    },
    workspaces: {
      title: 'Spații de lucru',
      description: 'Creează un spațiu de echipă, invită colegi și partajează foldere.',
      billingMetaTitle: 'Facturare spațiu · notai',
      billingTitle: 'Facturare spațiu',
      billingDescription:
        'Abonament per loc pentru acest spațiu. Tarifat per membru activ.',
    },
  },
  appFeatures: {
    ask: {
      stop: 'Oprește',
      ask: 'Întreabă',
      placeholder: 'Întreabă orice despre notele tale…',
      footnote: 'Notai îți citează notele după număr. Apasă o citare ca să deschizi sursa.',
      emptyTitle: 'Întreabă-ți al doilea creier',
      emptyBody:
        'Notai îți caută notele prin similaritate semantică, apoi scrie un răspuns argumentat, cu citări către notele-sursă.',
      suggestion1: 'Ce am învățat săptămâna asta?',
      suggestion2: 'Rezumă-mi notele recente de la întâlniri',
      suggestion3: 'Listează toate TODO-urile răspândite prin note',
      suggestion4: 'Care sunt întrebările mele deschise despre proiect?',
      recentQuestions: 'Întrebări recente',
      searching: 'Caut prin notele tale…',
      errorPrefix: 'Ceva n-a mers: {error}.',
      unknownError: 'eroare necunoscută',
      stopped: 'Oprit.',
      savingAnswer: 'Salvez răspunsul…',
      answerSaved: 'Răspuns salvat',
      saveAnswerTitle: 'Răspuns salvat',
      saveSourcesHeader: 'Surse',
      failedCreateNote: 'Nu am putut crea nota',
      copy: 'Copiază răspunsul',
      copied: 'Copiat',
      copyFailed: 'Nu am putut copia în clipboard',
      saveToNote: 'Salvează într-o notă nouă',
      sources: 'Surse:',
      untitled: 'Fără titlu',
    },
    graph: {
      hideEncrypted: 'Ascunde criptate',
      encryptedOnly: 'Doar criptate',
      graphAria: 'Graful notelor',
      empty: 'Încă nu ai note — începe să scrii și graful tău crește.',
      noEdgesBefore: 'Notele tale încă nu se referă una la alta. Tastează ',
      noEdgesAfter: ' într-o notă ca să începi legăturile — graful se umple pe parcurs.',
      someoneHere: '{name} e aici',
      someone: 'Cineva',
      viewerCountOther: '{count} persoane văd nota',
      outgoingIncoming: '{out} ies · {in} intră',
      moreOther: '+{count} altele',
    },
    inboxZero: {
      selectedCount: '{count} selectate',
      selectAll: 'Selectează tot',
      clear: 'Curăță',
      archive: 'Arhivează',
      moveToTrash: 'Mută în Coș',
      bulkDeleteConfirmOne: 'Muți {count} notă în Coș?',
      bulkDeleteConfirmOther: 'Muți {count} note în Coș?',
      movedToTrash: 'Mutate {count} în Coș.',
      archivedToastOne: 'Arhivată {count} notă.',
      archivedToastOther: 'Arhivate {count} note.',
      filed: 'Pusă la locul ei.',
      undo: 'Anulează',
      undoToast: 'Mutarea a fost anulată.',
      undoAll: 'Anulează tot',
      undoAllToast: 'Toate mutările au fost anulate.',
      filedManyOne: 'Pusă {count} notă la locul ei.',
      filedManyOther: 'Puse {count} note la locul lor.',
      readyAutoFileOne: '{count} notă gata de auto-filare (≥65% potrivire).',
      readyAutoFileOther: '{count} note gata de auto-filare (≥65% potrivire).',
      aiGistEach: 'Esență AI pentru fiecare',
      gistFailed: 'Nu am putut rezuma',
      fileAll: 'Filează toate',
      fileHere: 'Filează aici',
      suggested: 'Sugestie:',
      matchPercent: '({percent}% potrivire)',
      noClearMatch: 'Fără potrivire clară — alege un folder:',
      selectAria: 'Selectează {title}',
      untitled: 'Fără titlu',
      emptyHeading: 'Inbox zero.',
      emptyBody: 'Fiecare notă e la locul ei. Bravo.',
    },
    calendar: {
      previousMonth: 'Luna precedentă',
      nextMonth: 'Luna următoare',
      today: 'Astăzi',
      weekdayMon: 'Lun',
      weekdayTue: 'Mar',
      weekdayWed: 'Mie',
      weekdayThu: 'Joi',
      weekdayFri: 'Vin',
      weekdaySat: 'Sâm',
      weekdaySun: 'Dum',
      countTitleOne: '{count} notă actualizată',
      countTitleOther: '{count} note actualizate',
      loading: 'Se încarcă…',
      noNotes: 'Nicio notă actualizată în ziua asta.',
      untitled: 'Fără titlu',
    },
    voice: {
      title: 'Captură vocală',
      stopLabel: 'Oprește înregistrarea',
      recording: 'Înregistrez — apasă pentru a opri',
      transcribing: 'Transcriu…',
      requesting: 'Cer microfonul…',
      escHint: 'Apasă {key} ca să anulezi',
      tooShort: 'Înregistrarea a fost prea scurtă.',
      saved: 'Notă vocală salvată',
      micError: 'Nu am putut accesa microfonul',
    },
    workspace: {
      newPlaceholder: 'Nume spațiu nou…',
      create: 'Creează',
      created: 'Spațiu creat',
      createFailed: 'Nu s-a putut crea',
      none: 'Încă niciun spațiu.',
      roleOwner: 'proprietar',
      roleAdmin: 'admin',
      roleEditor: 'editor',
      roleViewer: 'vizitator',
      memberCountOne: '{count} membru',
      memberCountOther: '{count} membri',
      summary: '{role} · {members}',
      manage: 'Gestionează',
      hide: 'Ascunde',
      billingTitle: 'Facturare',
      deleteConfirm:
        'Ștergi „{name}”? Membrii pierd accesul imediat.',
      deleted: 'Șters',
      failed: 'A eșuat',
      loading: 'Se încarcă…',
      inviteEmailPlaceholder: 'invitat@exemplu.com',
      roleAdminOption: 'Admin',
      roleEditorOption: 'Editor',
      roleViewerOption: 'Vizitator',
      invite: 'Invită',
      inviteCopied: 'Link de invitație copiat pentru {email}',
      inviteCreated: 'Invitație creată: {url}',
      inviteFailed: 'Nu am putut invita',
      removeConfirm: 'Elimini pe {who}?',
      acceptInvite: 'Acceptă invitația',
      joined: 'Te-ai alăturat spațiului',
      acceptFailed: 'Nu am putut accepta',
      billing: {
        current: 'Curent',
        plan: 'Plan:',
        status: 'Stare:',
        seats: 'Locuri:',
        members: 'Membri:',
        cancels: 'Se anulează',
        renews: 'Se reînnoiește',
        renewLine: '{verb} pe {date}',
        manageTitle: 'Gestionează abonamentul',
        manageBody:
          'Schimbă locurile, ciclul de facturare sau anulează din portalul Stripe.',
        openPortal: 'Deschide portalul de facturare',
        upgradeTitle: 'Upgrade la Teams',
        seatsLabel: 'Locuri',
        cycleLabel: 'Ciclu',
        currencyLabel: 'Monedă',
        monthly: 'Lunar',
        yearly: 'Anual',
        memberCountOne:
          'Ai {count} membru. Cumpără cel puțin atâtea locuri.',
        memberCountOther:
          'Ai {count} membri. Cumpără cel puțin atâtea locuri.',
        checkout: 'Continuă spre plată',
      },
    },
    database: {
      title: 'Titlu',
      empty: 'Nicio notă nu are încă această proprietate.',
      untitled: 'Fără titlu',
    },
    review: {
      gradeAgainLabel: 'Din nou',
      gradeAgainHint: 'Ai uitat — arată curând',
      gradeHardLabel: 'Greu',
      gradeHardHint: 'Recuperat cu efort',
      gradeGoodLabel: 'Bine',
      gradeGoodHint: 'Recuperat',
      gradeEasyLabel: 'Ușor',
      gradeEasyHint: 'Banal',
      cardAdded: 'Card adăugat',
      deleted: 'Șters',
      deleteConfirm: 'Ștergi acest card?',
      tabReview: 'Recapitulare ({count})',
      tabAll: 'Toate cardurile',
      tabNew: 'Card nou',
      showAnswer: 'Arată răspunsul',
      noneDue: 'Niciun card scadent acum. Adaugă unele sau revino mai târziu.',
      noCards: 'Încă niciun card.',
      intervalDueLine: 'Interval: {days}z · Scadent {date}',
      delete: 'Șterge',
      frontLabel: 'Față',
      backLabel: 'Verso',
      frontPlaceholder: 'Întrebare sau indiciu',
      backPlaceholder: 'Răspuns',
      addCard: 'Adaugă card',
    },
  },
  dashboard: {
    morningBrief: {
      title: 'Briefingul dimineții',
      updatedAt: 'Actualizat {time}',
      privateLabel: 'Personal & privat',
      saveToToday: 'Salvează în azi',
      saveToTodayTitle: 'Salvează în nota zilei',
      refresh: 'Regenerează',
      refreshTitle: 'Regenerează',
      expand: 'Extinde',
      collapse: 'Restrânge',
      reading: 'Îți citesc notele recente…',
      drawnFrom: 'Pornit de la',
      askAbout: 'Întreabă despre asta',
      askPlaceholder: 'Ce e cel mai urgent azi?',
      ask: 'Întreabă',
      sectionHeading: 'Briefingul dimineții — {date}',
      ariaLabel: 'Briefingul dimineții',
    },
    throwback: {
      label: 'Reamintire',
      refreshLabel: 'Arată altă reamintire',
      refreshTitle: 'Arată alta',
      daysAgoOne: 'acum {count} zi',
      daysAgoOther: 'acum {count} zile',
      monthsAgoOne: 'acum o lună',
      monthsAgoOther: 'acum {count} luni',
      yearOne: 'acum un an',
      yearOther: 'acum {count} ani',
      yearsMonths: 'acum {years}a {months}l',
    },
    staleTodos: {
      label: 'TODO-uri uitate · neatinse de 14+ zile',
      untitled: 'Fără titlu',
    },
    streak: {
      titleActive: 'Ziua {current} din seria curentă. Recordul tău: {best}.',
      titleInactive:
        'Seria ta e la {current}. Scrie azi ca s-o ții vie — recordul tău: {best}.',
      streakLabel: 'serie de {days} zile',
      bestLabel: '· record {count}',
    },
    timeOfDay: {
      segmentEarlyMorning: 'Dimineață devreme',
      segmentMorning: 'Dimineața',
      segmentAfternoon: 'După-amiaza',
      segmentEvening: 'Seara',
      segmentNight: 'Noaptea',
      labelHours: '{hours}h {mins}m până {next}',
      labelMins: '{mins}m până {next}',
    },
    weeklyReview: {
      title: 'Recapitularea săptămânii',
      summary: '{touched} atinse · {created} noi',
      relativeToday: 'azi',
      relativeYesterday: 'ieri',
      relativeDaysAgo: 'acum {count}z',
      untitled: 'Fără titlu',
    },
    inboxZeroNudge: {
      titleOne: '{count} notă nefilată te așteaptă',
      titleOther: '{count} note nefilate te așteaptă',
      body: 'Filează-le într-o trecere — Notai sugerează un folder pentru fiecare.',
      cta: 'Inbox Zero',
    },
    continue: {
      title: 'Continuă de unde ai rămas',
      untitled: 'Fără titlu',
      justNow: 'chiar acum',
      minsAgo: 'acum {count}m',
      hoursAgo: 'acum {count}h',
      daysAgo: 'acum {count}z',
    },
    dailyPrompt: {
      label: 'Promptul de azi',
      refreshLabel: 'Reîmprospătează promptul',
      refreshTitle: 'Generează alt prompt',
      writeAbout: 'Scrie despre asta',
      creating: 'Se creează…',
      historyAria: 'Prompturi de jurnal recente',
      historyLabel: 'Istoric',
      historyEmpty: 'Încă niciun prompt vechi — vor apărea aici pe măsură ce revii.',
    },
    dailyRecap: {
      label: 'Recapitularea zilei',
      summary: '{notes} · {words} cuvinte',
      noteCountOne: '{count} notă',
      noteCountOther: '{count} note',
      refreshLabel: 'Regenerează recapitularea',
      refreshTitle: 'Regenerează recapitularea',
      saveAsNote: 'Salvează ca notă',
      noProvider: 'Conectează un furnizor AI în Setări ca să primești un rezumat de final de zi.',
    },
    sentimentHeatmap: {
      label: 'Dispoziție, ultimele 30 de zile',
      wroteOn: 'ai scris în {count} din 30 de zile',
      tooltipPositive: '{date}: pozitiv ({count} {noteWord})',
      tooltipTense: '{date}: tensionat ({count} {noteWord})',
      tooltipNeutral: '{date}: neutru ({count} {noteWord})',
      tooltipNothing: '{date}: nimic scris',
      noteWordOne: 'notă',
      noteWordOther: 'note',
      footer:
        'Colorat după sentimentul cuvintelor scrise. Rămâne pe serverul tău, fără apeluri AI externe.',
    },
    openLoops: {
      label: 'Fire deschise',
      untitled: 'Fără titlu',
    },
    autoArchive: {
      bodyOne: 'notă neatinsă de 90+ zile.',
      bodyOther: 'note neatinse de 90+ zile.',
      archiving: 'Se arhivează…',
      archiveAll: 'Arhivează toate',
      archivedToastOne: 'Arhivată {count} notă veche.',
      archivedToastOther: 'Arhivate {count} note vechi.',
      undo: 'Anulează',
      undoToast: 'Arhivarea a fost anulată.',
    },
    trashPurge: {
      bodyOne: 'notă',
      bodyOther: 'note',
      countLine: '{count} {word} în coș mai vechi de 30 de zile.',
      tail: 'Le ștergi definitiv ca să eliberezi spațiu?',
      working: 'Se lucrează…',
      emptyOld: 'Golește vechile',
      notNow: 'Nu acum',
      purgedOne: 'Ștersă definitiv {count} notă.',
      purgedOther: 'Șterse definitiv {count} note.',
      failed: 'Nu am putut goli coșul.',
      dismiss: 'Renunță',
    },
    todayTasks: {
      header: 'Azi · {count} scadente',
      priorityHigh: 'urgent',
      priorityMed: 'mediu',
      priorityLow: 'scăzut',
      estimateTitleOne: 'Estimat {count} minut',
      estimateTitleOther: 'Estimat {count} minute',
      yesterday: 'ieri',
      daysAgo: 'acum {count}z',
      todayLabel: 'azi',
      untitled: 'Fără titlu',
    },
    calendarToday: {
      title: 'În calendarul tău',
      manage: 'Gestionează',
      today: 'Astăzi',
      tomorrow: 'Mâine',
      next7Days: 'Următoarele 7 zile',
      allDay: 'toată ziua',
    },
    view: {
      sortUpdated: 'Modificate recent',
      sortCreated: 'Create recent',
      sortOpened: 'Deschise recent',
      sortAlphabetical: 'Alfabetic (A→Z)',
      sortCustom: 'Personalizat (trage pentru reordonare)',
      updatedAny: 'Oricând',
      updatedToday: 'Azi',
      updated7d: 'Ultimele 7 zile',
      updated30d: 'Ultimele 30 de zile',
      colorDefault: 'Implicit',
      colorYellow: 'Galben',
      colorPink: 'Roz',
      colorBlue: 'Albastru',
      colorGreen: 'Verde',
      colorPurple: 'Mov',
      colorOrange: 'Portocaliu',
      defaultName: 'Implicită',
      viewsLabel: 'Vizualizări',
      renameCurrent: 'Redenumește curentă',
      makeDefault: 'Setează ca implicită',
      deleteCurrent: 'Șterge curenta',
      saveAsNew: 'Salvează ca vizualizare nouă…',
      saveAsNewShort: 'Salvează ca nouă',
      saveView: 'Salvează vizualizarea',
      updateView: 'Actualizează vizualizarea',
      sortLabel: 'Sortare',
      sortBy: 'Sortează după',
      pinnedFirst: 'Fixate primele',
      filters: 'Filtre',
      filterSearch: 'Caută',
      filterStatus: 'Stare',
      filterKind: 'Tip',
      filterUpdated: 'Modificate',
      filterFolders: 'Foldere',
      filterTags: 'Etichete',
      filterColor: 'Culoare',
      filterOther: 'Altele',
      searchPlaceholder: 'Titlu sau conținut…',
      statusPinned: 'Fixate',
      statusPinnedOnToday: 'Pe Azi',
      statusFavorite: 'Favorite',
      statusArchived: 'Arhivate',
      kindNotes: 'Note',
      kindStickies: 'Stickies',
      noFolder: 'Fără folder',
      hasCollaborators: 'Cu colaboratori',
      reset: 'Resetează',
      saveDialogTitle: 'Salvează vizualizarea',
      saveDialogLabel: 'Nume',
      saveDialogPlaceholder: 'Favoritele mele',
      saveToast: 'Vizualizarea „{name}” a fost salvată',
      updateToast: 'Vizualizarea „{name}” a fost actualizată',
      renameDialogTitle: 'Redenumește vizualizarea',
      renameDialogLabel: 'Nume',
      deleteDialogTitle: 'Ștergi vizualizarea „{name}”?',
      deleteDialogBody: 'Acțiunea nu poate fi anulată.',
      deleteConfirm: 'Șterge',
      deleteToast: 'Vizualizare ștearsă',
      defaultToast: '„{name}” e acum vizualizarea implicită',
      pinnedOnToday: 'Fixată pe Azi',
      notesHeading: 'Note',
      noMatchTitle: 'Nicio notă nu se potrivește cu filtrele tale',
      noMatchBody: 'Ajustează filtrele sau resetează-le.',
      resetFilters: 'Resetează filtrele',
      dragLabel: 'Trage pentru a reordona',
      pinnedOnTodayTitle: 'Fixată pe Azi',
      switchedToCustom: 'Am trecut la ordine personalizată',
      reorderFailed: 'Reordonarea a eșuat: {error}',
    },
  },
};

function merge(target, patch) {
  for (const [k, v] of Object.entries(patch)) {
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      target[k] = target[k] && typeof target[k] === 'object' ? target[k] : {};
      merge(target[k], v);
    } else {
      target[k] = v;
    }
  }
  return target;
}

for (const [p, patch] of [
  [enPath, en],
  [roPath, ro],
]) {
  const j = JSON.parse(fs.readFileSync(p, 'utf8'));
  merge(j, patch);
  fs.writeFileSync(p, JSON.stringify(j, null, 2) + '\n', 'utf8');
  console.log('wrote', p);
}
